power <- read.table("household_power_consumption.txt",sep=";",header=TRUE,stringsAsFactors=F, na.strings="?")
power$Date <- as.Date(power$Date,format='%d/%m/%Y')
head(power$Date)
powerconsumption <- subset(power,Date%in%as.Date(c("2007-02-01","2007-02-02")))
powerconsumption$DateTime=as.POSIXct(paste(powerconsumption$Date,powerconsumption$Time))
powerconsumption$Global_active_power<-as.numeric(powerconsumption$Global_active_power)
png("plot3.png", width=480, height=480)
plot(powerconsumption$DateTime,powerconsumption$Sub_metering_1,xlab="",type="l",ylab="Energy sub metering")
lines(powerconsumption$DateTime,powerconsumption$Sub_metering_2,col="red")
lines(powerconsumption$DateTime,powerconsumption$Sub_metering_3,col="blue")
legend("topright", col=c("black", "red", "blue"), lty=1, lwd=2,legend=c("Sub_metering_1", "Sub_metering_2", "Sub_metering_3"))
dev.off()