power <- read.table("household_power_consumption.txt",sep=";",header=TRUE,stringsAsFactors=F, na.strings="?")
power$Date <- as.Date(power$Date,format='%d/%m/%Y')
head(power$Date)
powerconsumption <- subset(power,Date%in%as.Date(c("2007-02-01","2007-02-02")))
powerconsumption$DateTime=as.POSIXct(paste(powerconsumption$Date,powerconsumption$Time))
powerconsumption$Global_active_power<-as.numeric(powerconsumption$Global_active_power)
png("plot4.png", width=480, height=480)
par(mfrow=c(2,2))
plot(powerconsumption$DateTime,powerconsumption$Global_active_power,type="l",xlab="",ylab="Global Active Power (kilowatts)")
plot(powerconsumption$DateTime,powerconsumption$Voltage,type="l",xlab="datetime",ylab="Voltage")
plot(powerconsumption$DateTime,powerconsumption$Sub_metering_1,xlab="",type="l",ylab="Energy sub metering")
lines(x=powerconsumption$DateTime,y=powerconsumption$Sub_metering_2,col="red")
lines(x=powerconsumption$DateTime,y=powerconsumption$Sub_metering_3,col="blue")
legend("topright", col=c("black", "red", "blue"), lty=1, lwd=2,legend=c("Sub_metering_1", "Sub_metering_2", "Sub_metering_3"))
plot(powerconsumption$DateTime,powerconsumption$Global_reactive_power,type="l",xlab="datetime",ylab="Global_reactive_power")
dev.off()